const crypto = require('node:crypto');
const { createApp: createBaseApp } = require('./app.cjs');
const { parseRockstarStatsHtml } = require('./providers.cjs');

const TRN_GAMES = new Set(['apex','fortnite','halo']);
const ROCKSTAR_CATEGORIES = new Set(['Career','Skills','General','Crimes','Vehicles','Cash','Combat','Weapons']);
const SPOTIFY_SCOPES = ['user-read-private','user-read-email','user-read-currently-playing','user-read-recently-played','user-top-read'];

function error(res, status, message, details) { return res.status(status).json({ ok:false, error:message, details }); }
function admin(req,res,next){ const token=process.env.NEKODECK_API_TOKEN||''; if(!token||req.get('X-NekoDeck-Token')===token)return next(); return error(res,401,'Admin token required'); }
function cookie(value,name=''){ const raw=String(value||'').trim(); if(!raw)return ''; return raw.includes('=')||!name?raw:`${name}=${raw}`; }
function baseUrl(req){ const proto=String(req.get('x-forwarded-proto')||req.protocol).split(',')[0].trim(); const host=String(req.get('x-forwarded-host')||req.get('host')).split(',')[0].trim(); return `${proto}://${host}`; }
async function request(url, options={}) { const c=new AbortController(); const t=setTimeout(()=>c.abort(), options.timeout||12000); try { return await fetch(url,{...options,signal:c.signal,headers:{'user-agent':'NekoDeck/0.2 (+https://github.com/NekoSuneProjects/NekoDeck)',...(options.headers||{})}}); } finally { clearTimeout(t); } }
async function json(url, options={}) { const r=await request(url,{...options,headers:{accept:'application/json',...(options.headers||{})}}); const text=await r.text(); let data; try{data=text?JSON.parse(text):null}catch{data={raw:text.slice(0,1200)}} if(!r.ok){const e=new Error(`Upstream HTTP ${r.status}`);e.status=r.status;e.data=data;throw e} return data; }
async function text(url, options={}) { const r=await request(url,options); const body=await r.text(); if(!r.ok){const e=new Error(`Upstream HTTP ${r.status}`);e.status=r.status;e.data=body.slice(0,1200);throw e} return body; }

function registerV2(app, store) {
  const get=(id,type)=>{const i=store.getPrivateInstance(id);return i&&(!type||i.templateId===type)?i:null};
  app.post('/api/v2/instances', admin, (req,res)=>{
    const b=req.body||{}; if(!b.templateId||!b.name||!b.discordClientId||!b.discordClientSecret)return error(res,400,'Template, name, Discord Client ID and Client Secret are required');
    const needs={trn:['providerApiKey'],steam:['providerApiKey'],lastfm:['providerApiKey'],rockstar:['providerSession'],vrchat:['providerSession'],spotify:['providerClientId','providerClientSecret']}[b.templateId]||[];
    for(const k of needs) if(!String(b[k]||'').trim()) return error(res,400,`${k} is required for ${b.templateId}`);
    const credentials={discordClientId:String(b.discordClientId).trim(),discordClientSecret:String(b.discordClientSecret).trim(),botToken:String(b.botToken||'').trim(),providerApiKey:String(b.providerApiKey||'').trim(),providerClientId:String(b.providerClientId||'').trim(),providerClientSecret:String(b.providerClientSecret||'').trim(),providerSession:String(b.providerSession||'').trim()};
    res.status(201).json({ok:true,instance:store.createInstance({templateId:b.templateId,name:String(b.name).trim(),config:b.config&&typeof b.config==='object'?b.config:{},credentials})});
  });
  app.put('/api/v2/instances/:id/credentials', admin, (req,res)=>{const allowed=['discordClientId','discordClientSecret','botToken','providerApiKey','providerClientId','providerClientSecret','providerSession'];const patch={};for(const k of allowed)if(typeof req.body?.[k]==='string'&&req.body[k].trim())patch[k]=req.body[k].trim();const i=store.mergeCredentials(req.params.id,patch);return i?res.json({ok:true,instance:i}):error(res,404,'Widget instance not found')});
  app.put('/api/v2/instances/:id/config', admin, (req,res)=>{const p=req.body&&typeof req.body==='object'&&!Array.isArray(req.body)?req.body:{};const i=store.updateConfig(req.params.id,p);return i?res.json({ok:true,instance:i}):error(res,404,'Widget instance not found')});

  app.get('/api/widgets/trn/:id/player', async(req,res)=>{const i=get(req.params.id,'trn');if(!i)return error(res,404,'TRN widget not found');const game=String(req.query.game||'apex').toLowerCase(),player=String(req.query.player||'').trim(),platform=String(req.query.platform||'origin').trim();if(!player)return error(res,400,'Player is required');if(!TRN_GAMES.has(game))return error(res,400,'Supported modes: apex, fortnite, halo');if(game!=='apex')return res.json({ok:true,mode:'profile-link',game,player,notice:`TRN does not currently expose a public ${game} stats API. NekoDeck will not scrape Tracker.gg.`,trackerUrl:`https://tracker.gg/search?q=${encodeURIComponent(player)}`});try{const data=await json(`https://public-api.tracker.gg/v2/apex/standard/profile/${encodeURIComponent(platform)}/${encodeURIComponent(player)}`,{headers:{'TRN-Api-Key':i.credentials.providerApiKey}});res.json({ok:true,trn:data.data})}catch(e){error(res,e.status||502,'Tracker Network request failed',e.data||e.message)}});

  app.get('/api/widgets/steam/:id/player', async(req,res)=>{const i=get(req.params.id,'steam');if(!i)return error(res,404,'Steam widget not found');let id=String(req.query.player||req.query.steamid||'').trim();if(!id)return error(res,400,'SteamID64 or vanity name is required');try{const key=i.credentials.providerApiKey;if(!/^\d{17}$/.test(id)){const r=await json(`https://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=${encodeURIComponent(key)}&vanityurl=${encodeURIComponent(id)}`);id=String(r.response?.steamid||'')}if(!id)return error(res,404,'Steam profile could not be resolved');const [p,g]=await Promise.all([json(`https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=${encodeURIComponent(key)}&steamids=${id}`),json(`https://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=${encodeURIComponent(key)}&steamid=${id}&format=json&include_appinfo=1&include_played_free_games=1`).catch(()=>({response:{}}))]);const games=g.response?.games||[];res.json({ok:true,steam:{steamId:id,profile:p.response?.players?.[0]||null,gameCount:g.response?.game_count??games.length,totalPlaytimeHours:Math.round(games.reduce((n,x)=>n+(x.playtime_forever||0),0)/6)/10,topGames:[...games].sort((a,b)=>(b.playtime_forever||0)-(a.playtime_forever||0)).slice(0,10)}})}catch(e){error(res,e.status||502,'Steam request failed',e.data||e.message)}});

  app.get('/api/widgets/lastfm/:id/user', async(req,res)=>{const i=get(req.params.id,'lastfm');if(!i)return error(res,404,'Last.fm widget not found');const user=String(req.query.user||'').trim();if(!user)return error(res,400,'Last.fm username is required');const call=(method,extra='')=>json(`https://ws.audioscrobbler.com/2.0/?method=${method}&user=${encodeURIComponent(user)}&api_key=${encodeURIComponent(i.credentials.providerApiKey)}&format=json${extra}`);try{const [info,recent,artists,tracks]=await Promise.all([call('user.getInfo'),call('user.getRecentTracks','&limit=10'),call('user.getTopArtists','&limit=8&period=overall'),call('user.getTopTracks','&limit=8&period=overall')]);res.json({ok:true,lastfm:{user:info.user,recentTracks:recent.recenttracks?.track||[],topArtists:artists.topartists?.artist||[],topTracks:tracks.toptracks?.track||[]}})}catch(e){error(res,e.status||502,'Last.fm request failed',e.data||e.message)}});

  app.get('/api/widgets/vrchat/:id/me', async(req,res)=>{const i=get(req.params.id,'vrchat');if(!i)return error(res,404,'VRChat widget not found');const c=cookie(i.credentials.providerSession,'auth');if(!c)return error(res,409,'VRChat auth cookie is not configured');try{const u=await json('https://api.vrchat.cloud/api/1/auth/user',{headers:{cookie:c}});res.json({ok:true,experimental:true,vrchat:{id:u.id,displayName:u.displayName,username:u.username,bio:u.bio,status:u.status,statusDescription:u.statusDescription,state:u.state,dateJoined:u.date_joined,lastLogin:u.last_login,lastActivity:u.last_activity,lastPlatform:u.last_platform,profilePic:u.profilePicOverride||u.currentAvatarThumbnailImageUrl||u.userIcon,pronouns:u.pronouns,tags:u.tags||[],friends:Array.isArray(u.friends)?u.friends.length:0,onlineFriends:Array.isArray(u.onlineFriends)?u.onlineFriends.length:0,activeFriends:Array.isArray(u.activeFriends)?u.activeFriends.length:0,offlineFriends:Array.isArray(u.offlineFriends)?u.offlineFriends.length:0}})}catch(e){error(res,e.status||502,e.status===401?'VRChat session expired or invalid':'VRChat request failed',e.data||e.message)}});

  app.get('/api/widgets/rockstar/:id/stats', async(req,res)=>{const i=get(req.params.id,'rockstar');if(!i)return error(res,404,'Rockstar widget not found');const nickname=String(req.query.nickname||'').trim();if(!nickname)return error(res,400,'Social Club nickname is required');const raw=String(req.query.category||'Skills');const category=[...ROCKSTAR_CATEGORIES].find(x=>x.toLowerCase()===raw.toLowerCase())||'Skills';const c=cookie(i.credentials.providerSession);try{const q=new URLSearchParams({character:'Freemode',category,nickname,slot:'Freemode',gamerHandle:'',gamerTag:'',_:String(Date.now())});const body=await text(`https://socialclub.rockstargames.com/games/gtav/StatsAjax?${q}`,{headers:{accept:'text/html, */*; q=0.01',cookie:c,'x-requested-with':'XMLHttpRequest'}});if(/sign in to social club|\/profile\/signin|requestverificationtoken/i.test(body))return error(res,401,'Social Club session expired; update the encrypted cookie');const p=parseRockstarStatsHtml(body);res.json({ok:true,experimental:true,rockstar:{nickname,category,parsedStats:p.stats,textLines:p.lines,responseBytes:Buffer.byteLength(body)}})}catch(e){error(res,e.status||502,'Rockstar Social Club request failed',e.data||e.message)}});

  app.get('/api/widgets/spotify/:id/connect', admin, (req,res)=>{const i=get(req.params.id,'spotify');if(!i)return error(res,404,'Spotify widget not found');const redirectUri=`${baseUrl(req)}/api/widgets/spotify/${i.id}/callback`,state=crypto.randomBytes(24).toString('base64url');store.mergeCredentials(i.id,{spotifyOauthState:state,spotifyRedirectUri:redirectUri});const q=new URLSearchParams({response_type:'code',client_id:i.credentials.providerClientId,scope:SPOTIFY_SCOPES.join(' '),redirect_uri:redirectUri,state,show_dialog:'true'});res.json({ok:true,authUrl:`https://accounts.spotify.com/authorize?${q}`,redirectUri,scopes:SPOTIFY_SCOPES})});
  app.get('/api/widgets/spotify/:id/callback', async(req,res)=>{const i=get(req.params.id,'spotify');if(!i)return res.status(404).send('Spotify widget not found');if(!req.query.code||req.query.state!==i.credentials.spotifyOauthState)return res.status(400).send('Invalid Spotify OAuth callback/state');try{const body=new URLSearchParams({code:String(req.query.code),redirect_uri:i.credentials.spotifyRedirectUri,grant_type:'authorization_code'}),r=await request('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',authorization:`Basic ${Buffer.from(`${i.credentials.providerClientId}:${i.credentials.providerClientSecret}`).toString('base64')}`},body}),d=await r.json();if(!r.ok)return res.status(r.status).send(`Spotify token exchange failed: ${d.error_description||d.error}`);store.mergeCredentials(i.id,{accessToken:d.access_token,refreshToken:d.refresh_token,accessTokenExpiresAt:Date.now()+Number(d.expires_in||3600)*1000,spotifyOauthState:''});res.type('html').send('<meta charset="utf-8"><body style="font-family:system-ui;background:#07120d;color:#eafff2;padding:40px"><h1>Spotify connected ✓</h1><p>Return to NekoDeck.</p></body>')}catch(e){res.status(502).send(`Spotify OAuth failed: ${e.message}`)}});
  async function spotifyToken(id){let i=get(id,'spotify');if(!i)throw Object.assign(new Error('Spotify widget not found'),{status:404});if(i.credentials.accessToken&&Number(i.credentials.accessTokenExpiresAt||0)>Date.now()+60000)return i.credentials.accessToken;if(!i.credentials.refreshToken)throw Object.assign(new Error('Spotify is not connected yet'),{status:409});const body=new URLSearchParams({grant_type:'refresh_token',refresh_token:i.credentials.refreshToken}),r=await request('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',authorization:`Basic ${Buffer.from(`${i.credentials.providerClientId}:${i.credentials.providerClientSecret}`).toString('base64')}`},body}),d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error_description||d.error||'Spotify refresh failed'),{status:r.status,data:d});store.mergeCredentials(id,{accessToken:d.access_token,accessTokenExpiresAt:Date.now()+Number(d.expires_in||3600)*1000,...(d.refresh_token?{refreshToken:d.refresh_token}:{})});return d.access_token}
  app.get('/api/widgets/spotify/:id/profile', async(req,res)=>{try{const token=await spotifyToken(req.params.id),headers={authorization:`Bearer ${token}`},parts=await Promise.allSettled([json('https://api.spotify.com/v1/me',{headers}),json('https://api.spotify.com/v1/me/player/currently-playing',{headers}),json('https://api.spotify.com/v1/me/player/recently-played?limit=8',{headers}),json('https://api.spotify.com/v1/me/top/tracks?limit=8&time_range=medium_term',{headers})]),val=n=>parts[n].status==='fulfilled'?parts[n].value:null;res.json({ok:true,spotify:{profile:val(0),currentlyPlaying:val(1),recent:val(2)?.items||[],topTracks:val(3)?.items||[],partialErrors:parts.map((x,n)=>x.status==='rejected'?{index:n,message:x.reason?.message}:null).filter(Boolean)}})}catch(e){error(res,e.status||502,'Spotify request failed',e.data||e.message)}});
}

function createApp(options={}) { const out=createBaseApp(options); registerV2(out.app,out.store); return out; }
module.exports={createApp,registerV2};
